# Generated by Django 5.0.3 on 2024-04-09 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comemnt_text',
            new_name='comment_text',
        ),
    ]
